---
title: "Testing EnhancedVolcano on own data"
output:
  html_document:
    df_print: paged
---

```{r}
suppressPackageStartupMessages({
  library(EnhancedVolcano)
  library(magrittr)
  library('DESeq2')
  library("BiocParallel")
})
```


```{r}
res <- readRDS("shrunken.RDS")
row_names <- rownames(res)
gene_annotations_df <- read.table(file = 'each_gene_in_one_row.tsv', sep = '\t', header = TRUE, stringsAsFactors = FALSE)

create_gene_symbols_list <- function(gene_annotations_df, names = "Genes", values = "Gene_name"){
  # Building a name/value association list
  IDs_symbols_mapping <- list()
  keys <- as.vector(gene_annotations_df[[names]])
  vals <- as.vector(gene_annotations_df[[values]])
  IDs_symbols_mapping[keys] <- vals
  return(IDs_symbols_mapping)
}

fill_nas_with_gene_IDs <- function(IDs_symbols_mapping){
  for (i in  1:length(IDs_symbols_mapping)){
    if(is.na(IDs_symbols_mapping[[i]])){
      gene_ID <- names(IDs_symbols_mapping)[i]
      IDs_symbols_mapping[i] <- gene_ID
    }
  }
  return(IDs_symbols_mapping)
}

find_matching_indexes <- function(all_geneIDs, de_geneIDs_mapping){
  gene_names <- unlist(de_geneIDs_mapping)
  gene_ID_indexes <- match(all_geneIDs, names(gene_names))
  return(gene_ID_indexes)
}


replace_gene_IDs_with_gene_symbols <- function(indexes_of_DE_genes, all_geneIDs, IDs_symbols_mapping){
  # Go through all indexes of DE genes in the main geneIDs vector
  for (i in  1:length(indexes_of_DE_genes)){
    index <- indexes_of_DE_genes[i]
    # Assign gene symbol (if it exists) in the place of gene ID
    if(!is.na(index)){
      all_geneIDs[i] <- IDs_symbols_mapping[[index]]
    }
  }
  return(all_geneIDs)
}

de_geneIDs_symbols_mapping <- fill_nas_with_gene_IDs(create_gene_symbols_list(gene_annotations_df))
gene_ID_indexes <- find_matching_indexes(row_names, de_geneIDs_symbols_mapping)
rownames(res) <- replace_gene_IDs_with_gene_symbols(gene_ID_indexes, row_names, de_geneIDs_symbols_mapping)
```


```{r}
EnhancedVolcano(res,
  lab = rownames(res),
  x = 'log2FoldChange',
  y = 'padj',
  ylim = c(0,13),
  ylab = bquote(-~Log[10]~ 'Adj P'),
  title = "Volcanoplot",
  subtitle = "",
  legendPosition = 'right',
  legendLabels=c(' Not sig.',
                 bquote(~Log[2]~'FC'), 
                 ' p-value',
                 bquote(' p-value &' ~Log[2]~'FC')),
  legendLabSize = 12,
  col = c("#000000", "#E69F00", "#56B4E9", "#882255"),
  drawConnectors = TRUE,
  widthConnectors = 0.75
  )
```




