# Parameters used for Differential Expression analysis
DE:
    # This is used with counts.raw.txt and subread_counts.txt
    # Experimental_design: "conf/experiment_metadata.tsv"
    # This is used only with STAR_counts_all.csv data file
    Experimental_design: "conf/experiment_metadata_STAR_counts_all.tsv"
    Exp_design_unique_column: "Sample_ID"
    p-adj: 0.01
    volcano_top_genes: 50
    # Use the default (Benjamini & Hochberg) adjustment method of p-values for multiple comparisons
    pAdjustMethod: "bonferroni"
    # Contrasts for the deseq2 results method. The contrast must be comprised of 
    # a concatenation with " " of metadata's Condition and Phenotype columns
    contrasts:
        # name of numerator level for the fold change (level to compare)
        - "18/6 Short winged"
        # name of denominator level for the fold change (base level)
        - "12/12 Long winged"

software: 
    threads:
        default: 1
