
DE:
    Experimental_design: "conf/experiment_metadata.tsv"
    p-adj: 0.01
    volcano_top_genes: 96
    pAdjustMethod: "bonferroni"
    # Contrasts for the deseq2 results method
    contrasts:
        # log_2(18_Short_winged/12_Long_winged)
        # name of numerator level for the fold change (level to compare)
        - "18_Short_winged"
        # name of denominator level for the fold change (base level)
        - "12_Long_winged"

threads:
    DEseq2: 7

GSEA:
    p_value: 0.05
    GOcategories:
        - "BP"
        - "MF"
        - "CC"
    GOhierarchyTraversingAlgorithms:
        - "classic"
        - "elim"
        - "weight01"
        - "parentchild"
        - "weight"
        - "lea"
